import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RootLayoutClient from "./layout.uc";
import "./globals.css";
import Header from "@/components/header/Header";

interface Props {
  children: React.ReactNode;
}

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={font.className}>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
